version: '3'

services:
  api_server:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ../../app:/src
      - ../../data:/data
    environment:
      - NODE_ENV=development
    ports:
      - "8000:8000"
    command:
      [
        "python",
        "/src/data_io/servers/emnist_classifier_pred_server.py"
      ]
  api_client:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ../../app:/src
      - ../../data:/data
    environment:
      - NODE_ENV=development
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh api_server:8000 -t 10
        python /src/data_io/clients/emnist_classifier_pred_client.py
