version: '3'

services:
  api_server:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ../../app:/src
      - ../../data:/data
    environment:
      - NODE_ENV=development
    ports:
      - "8000:8000"
    command:
      [
        "python",
        "/src/data_io/servers/para_recognizer_pred_server.py"
      ]
