version: '3'

services:
  train:
    build:
      context: .
      dockerfile: train/Dockerfile
    volumes:
      - ../../app:/src
      - ../../data:/data
    environment:
      - NODE_ENV=development
    # runtime: nvidia
    command: [ "python", "/src/training/run_experiment.py" ]
